DROP TABLE GRUPO_PRODUTO;
DROP TABLE LOTE;
DROP TABLE LOTE_PRODUTO;
DROP TABLE PERFIL;
DROP TABLE PERFIL_USUARIO;
DROP TABLE USUARIO;


USE CONTROLEESTOQUE;

CREATE TABLE GRUPO_PRODUTO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME NVARCHAR(50) NOT NULL,
	DESCRICAO NVARCHAR(255) NOT NULL,
	ATIVO BIT NOT NULL,
	
	CONSTRAINT PK_GRUPO_PRODUTO PRIMARY KEY (ID)
);

GO

CREATE TABLE LOTE(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME NVARCHAR(10) NOT NULL,
	QTD_PRODUTO INT NOT NULL,
	TEMPERATURA FLOAT NOT NULL,
	BULA NVARCHAR(255) NOT NULL,
	VALIDADE DATE NOT NULL,
	ENTRADA DATE NOT NULL,
	
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID)
);

GO

CREATE TABLE PERFIL(
	 ID   INT IDENTITY(1,1) NOT NULL,
	 NOME   NVARCHAR (255) NOT NULL,
	 ATIVO   BIT  NOT NULL,
	
	CONSTRAINT  PK_PERFIL  PRIMARY KEY ( ID )
)

GO

CREATE TABLE USUARIO(
	 ID   int  IDENTITY(1,1) NOT NULL,
	 LOGIN   NVARCHAR (50) NOT NULL,
	 SENHA   NVARCHAR (32) NOT NULL,
	 NOME   NVARCHAR (100) NOT NULL,
	 ID_PERFIL   int  NOT NULL,
	
	CONSTRAINT  PK_USUARIO  PRIMARY KEY ( ID )
)

GO

CREATE TABLE PERFIL_USUARIO(
	
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PERFIL INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	
	CONSTRAINT PK_PERFIL_USUARIO PRIMARY KEY(ID),
	CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY(ID_PERFIL) REFERENCES PERFIL(ID),
	CONSTRAINT FP_USUARIO_PERFIL FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
)

GO

CREATE TABLE LOTE_PRODUTO(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_LOTE INT NOT NULL,
	ID_GRUPO INT NOT NULL,
	
	CONSTRAINT PK_LOTE_PRODUTO PRIMARY KEY(ID),
	CONSTRAINT FK_LOTE_PRODUTO FOREIGN KEY(ID_LOTE) REFERENCES LOTE(ID),
	CONSTRAINT FK_PRODUTO_LOTE FOREIGN KEY(ID_GRUPO) REFERENCES GRUPO_PRODUTO(ID)
);

GO

CREATE TABLE PACIENTE(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME NVARCHAR(255) NOT NULL,
	CPF NVARCHAR(255) NOT NULL,
	RG NVARCHAR(255) NOT NULL,
	CODIGO_RECEITA INT NOT NULL,
	TELEFONE INT NOT NULL,
	CEP INT NOT NULL,
	EMAIL NVARCHAR(255) NOT NULL,
	
	CONSTRAINT PK_PACIENTE PRIMARY KEY(ID)
);

GO

CREATE TABLE PACIENTE_LOTE(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PACIENTE INT NOT NULL,
	ID_LOTE INT NOT NULL,
	
	CONSTRAINT PK_PACIENTE_LOTE PRIMARY KEY(ID),
	CONSTRAINT FK_PACIENTE_LOTE FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_LOTE_PACIENTE FOREIGN KEY(ID_LOTE) REFERENCES LOTE(ID) 
);